[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
chrono = "0.4"
